# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft Properties
modloader=forge
minecraft_version=1.18.2
forge_version=40.2.0
yarn_mappings=1.18.2+build.4

# Mod Properties
mod_version=1.0.1.0
maven_group=net.quackimpala7321.crafter
archives_base_name=Crafter-Backport
loom.platform=forge
