modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="crafter"
version="1.0.0.1"
displayName="Crafter"
authors="QuackImpala7321, DerexXD"
description="Backports the Crafter from 1.21"

[[dependencies.crafter]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crafter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
