plugins {
    id 'java-library'
    id 'com.gtnewhorizons.retrofuturagradle' version '1.4.9'
}

version = "1.0.0-1.12.2"
group = "net.quackimpala7321.crafter"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

minecraft {
    mcVersion = '1.12.2'
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'
}

repositories {
    mavenCentral()
    maven {
        name = 'Forge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'Cleanroom'
        url = 'https://maven.cleanroommc.com'
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "1.12.2"

    filesMatching("mcmod.info") {
        expand "version": project.version, "mcversion": "1.12.2"
    }
}