modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="crafter"
version="1.0.1.0"
displayName="Crafter"
authors="QuackImpala7321, DerexXD"
description="Backports the Crafter from 1.21"

[[dependencies.crafter]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crafter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
