# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft Properties
modloader=forge
minecraft_version=1.19.2
forge_version=43.4.0

# Mod Properties
mod_version=1.0.0.1
maven_group=net.quackimpala7321.crafter
archives_base_name=crafter