# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft Properties
modloader=forge
minecraft_version=1.16.5
forge_version=36.2.39
yarn_mappings=1.16.5+build.10

# Mod Properties
mod_version=1.0.0.1
maven_group=net.quackimpala7321.crafter
archives_base_name=Crafter-Backport
loom.platform=forge
